### ISSUE TITLE
Inclusivity

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/governance#4]
In my opinion, it is a shame that the AMIA Open Source Governance team does include only males. I strongly suggest to be more inclusive.

**Comment by retokromer** [comment]
This seems to apply «only» to the «Governance Interest Group». To me this is confusing and I suggest to mention also all the team members in the README file. Sorry for the noise!

**Comment by privatezero** [comment]
Hi @retokromer! I agree that any ongoing governance group should be more inclusive in a variety of ways!

Currently, the interim interest group, besides lacking gender diversity is also composed only of volunteers who could be physically at the open source meeting, which is problematic for a whole bunch of reasons. (Such as creating geographic and fiscal barriers to participation).

This is why, once the initial work of making some infrastructural changes is done, this group will disband and volunteers for ongoing maintenance will be solicited via open channels, with the goal of having a sustainable system of maintenance that matches the inclusionary atmosphere that has been fostered within the AMIA-OS repositories themselves. Speaking for myself, I would consider it a failure if any future group did not reflect this diversity and these values!

**Comment by retokromer** [comment]
@privatezero Thanks for your answer! I did not understand that there were two groups and therefore I opened the issue. In my life, since working for the ICRC in many African countries back in the mid-1980s, I always made the experience that gender-mixed teams are much better – in all regards.

**Comment by retokromer** [comment]
@privatezero FYI: I did try to add a MIT license for the formulae in `homebrew-amiaos`, but I cannot open the PR, because the button is disabled. I also did try to open a PR for adding the Contributor Covenant CoC there, but I don’t know an email where to report (and I suspect the button would be disabled as well).
