### ISSUE TITLE
broken link?

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/governance#5]
The link https://github.com/amiaopensource/open-workflows/settings/collaboration mentioned in the README.md gives me a 404 error.

**Comment by privatezero** [comment]
Hi @retokromer, can you confirm that you are still getting a 404? Currently it redirects me to a login, but then takes me to the page as expected

**Comment by retokromer** [comment]
@privatezero Yes, I still get (I am already logged in): 

<img width="1099" alt="Screenshot 2019-06-10 at 19 48 33" src="https://user-images.githubusercontent.com/3246607/59248342-64d57c00-8c22-11e9-95b9-96183c496891.png">

**Comment by retokromer** [comment]
@privatezero I guess, `. . ./settings/. . .` is accessible only for administrators.

**Comment by privatezero** [comment]
Interesting! Thank you for catching that!

**Comment by dericed** [comment]
fixed in https://github.com/amiaopensource/governance/pull/6
