### ISSUE TITLE
Transferring repo to amiaopensource

### ISSUE THREAD

**Issue by nkrabben** [amiaopensource/governance#7]
I'd like to transfer https://github.com/nkrabben/av-python-carpentry/ to this org as a more appropriate home than my personal repo. Ben and I would still be maintainers.

However, I can't transfer it because I don't have permission to create repos here. Any suggested ways to work around this?

**Comment by privatezero** [comment]
I _believe_ that you can just go ahead and initiate the transfer through the settings tab. That should ping us and we can then accept the transfer and re-add you both as maintainers on this end.

**Comment by nkrabben** [comment]
I get an error message
"You don’t have the permission to create public repositories on amiaopensource"

**Comment by privatezero** [comment]
Ahh in diving deeper into the Github docs, yes that does seem to be a limitation. I'll elevate you for the transfer!

**Comment by privatezero** [comment]
Oh hah! Looks like elevation shouldn't be required - looks like you weren't a member. Invitation sent! I believe as a member you should have the access you need to create a repo. If it turns out otherwise, we can fix that!

**Comment by todrobbins** [comment]
A beautiful exchange!

**Comment by nkrabben** [comment]
Phew, looks like it's all working now. https://amiaopensource.github.io/av-python-carpentry/

For anyone doing this in the future, transfer is easy. Redirecting any gh-pages links is much harder.
1. Create a repo for the user/project named user/project.github.io
2. Add the jekyll-redirect-from gem to the configuration
3. Create a redirect template
4. Create a subdirectory for the old github.io url in the repo
5. Add markdown pages for each page using the template
6. Add a link to the new location on your 404 just in case

There's probably a better way of doing, I hope.

**Comment by privatezero** [comment]
Rad! Thank you! Let us know if any permissions issues crop up and we'll get ya sorted!
